### ISSUE TITLE
How to trigger vscode snippets?

### ISSUE THREAD

**Issue by danielo515** [D-Nice/vindi#16]
I find the ability of using VSCode snippets.
However, when I open a javascript file I can't use any of the built in snippets this repo has (from xabikos/vscode-javascript).
Do I need to do something special to trigger them?

Thanks and regards

**Comment by D-Nice** [comment]
Hi Danielo, thanks for giving it a try.

The snippets should show up in the autocomplete. I have tried them on a new PC just now, and they worked.

My steps:

1. Run vindi in root path of a js project.
2. `F8` to open NERDTree and then open src, and index.js (or create file using `m-a` in NERDTree). I open with `t`, so it goes in its own new tab, can open split with `s`.
3. Enter insert mode on the .js file and type one of the snippet prefixes outlined on the plugin page. I tried `imp` and `fre` and they both show their respective snippet among the autocompletion choices.
4. Hover over said snippet, by selecting it with `TAB` or `Shift-TAB` and then triggering it with `ENTER` or `C-Space`.

![vindi_snippets](https://user-images.githubusercontent.com/2888248/72932600-10ed5280-3d2e-11ea-9abf-aed1182a21e8.png)

Appreciate feedback if it works or not.

**Comment by danielo515** [comment]
Yes, it works for me now.
Maybe it is related to where I opened the editor? I just opened it on my root home directory and then navigated using nerd tree to a project folder.

By the way, I took a look at the nerd-tree help and I didn't saw that `m-a` command, is it a custom one?

Thank you very much for all your help

**Comment by D-Nice** [comment]
> Maybe it is related to where I opened the editor?

It should be related as to whether the active file/buffer in question is identified as a javascript file. You can do `:setf javascript` on a blank, unidentified, or non-standard js extension, to enable all JS related plugins on it.

> By the way, I took a look at the nerd-tree help and I didn't saw that m-a command, is it a custom one?

Vindi tries to be as close to vanilla vim as possible, and to plugin keybindings. I do believe `m-a` is a standard NERDTree command. Any binding maps or remaps should be findable here by searching for occurrences of `map`in the config file -> https://github.com/D-Nice/vindi/blob/master/etc/init/.config/nvim/init.vim

I'll consider this issue resolved for now

**Comment by danielo515** [comment]
> Vindi tries to be as close to vanilla vim as possible,

That is what I like so much about it

> I'll consider this issue resolved for now

Sure. Thank you very much for your support.
